//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ServiceStack;
using System.Collections.Generic;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class GetUserInfoRequest : IReturn<GetUserInfoResponse>
{

    private string userPhoneField;

    private string passwordField;

    private RequestHead headField;

    /// <remarks/>
    public string UserPhone
    {
        get
        {
            return this.userPhoneField;
        }
        set
        {
            this.userPhoneField = value;
        }
    }

    /// <remarks/>
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    public RequestHead Head
    {
        get
        {
            return this.headField;
        }
        set
        {
            this.headField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class RequestHead
{

    private string queryStringField;

    private string deviceIDField;

    /// <remarks/>
    public string QueryString
    {
        get
        {
            return this.queryStringField;
        }
        set
        {
            this.queryStringField = value;
        }
    }

    /// <remarks/>
    public string DeviceID
    {
        get
        {
            return this.deviceIDField;
        }
        set
        {
            this.deviceIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class UserRecordLogEntity
{

    private int commonCountField;

    private int giveCountField;

    private System.DateTime logDateField;

    /// <remarks/>
    public int CommonCount
    {
        get
        {
            return this.commonCountField;
        }
        set
        {
            this.commonCountField = value;
        }
    }

    /// <remarks/>
    public int GiveCount
    {
        get
        {
            return this.giveCountField;
        }
        set
        {
            this.giveCountField = value;
        }
    }

    /// <remarks/>
    public System.DateTime LogDate
    {
        get
        {
            return this.logDateField;
        }
        set
        {
            this.logDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class RechargeLogEntity
{

    private string rechargeCodeField;

    private int rechargeResultField;

    private decimal rechargeMoneyField;

    private System.DateTime rechargeDateField;

    /// <remarks/>
    public string RechargeCode
    {
        get
        {
            return this.rechargeCodeField;
        }
        set
        {
            this.rechargeCodeField = value;
        }
    }

    /// <remarks/>
    public int RechargeResult
    {
        get
        {
            return this.rechargeResultField;
        }
        set
        {
            this.rechargeResultField = value;
        }
    }

    /// <remarks/>
    public decimal RechargeMoney
    {
        get
        {
            return this.rechargeMoneyField;
        }
        set
        {
            this.rechargeMoneyField = value;
        }
    }

    /// <remarks/>
    public System.DateTime RechargeDate
    {
        get
        {
            return this.rechargeDateField;
        }
        set
        {
            this.rechargeDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class FriendsEntity
{

    private int addResultField;

    private int addTypeField;

    private string addRequestField;

    private UserInfoEntity userInfoField;

    /// <remarks/>
    public int AddResult
    {
        get
        {
            return this.addResultField;
        }
        set
        {
            this.addResultField = value;
        }
    }

    /// <remarks/>
    public int AddType
    {
        get
        {
            return this.addTypeField;
        }
        set
        {
            this.addTypeField = value;
        }
    }

    /// <remarks/>
    public string AddRequest
    {
        get
        {
            return this.addRequestField;
        }
        set
        {
            this.addRequestField = value;
        }
    }

    /// <remarks/>
    public UserInfoEntity UserInfo
    {
        get
        {
            return this.userInfoField;
        }
        set
        {
            this.userInfoField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetUserInfoResponse))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class UserInfoEntity
{

    private string userPhoneField;

    private int userSexField;

    private string passwordField;

    private int shareLocationField;

    private string userNickNameField;

    private byte[] userHeadPicField;

    private double userLatField;

    private double userLonField;

    private int[] userInterestField;

    private string thirdAccountField;

    private string deviceIDField;

    private int isOnlineField;

    private System.DateTime lastOnlineField;

    private int provinceIDField;

    private string provinceNameField;

    private int cityIDField;

    private string cityNameField;

    private decimal userBalanceField;

    /// <remarks/>
    public string UserPhone
    {
        get
        {
            return this.userPhoneField;
        }
        set
        {
            this.userPhoneField = value;
        }
    }

    /// <remarks/>
    public int UserSex
    {
        get
        {
            return this.userSexField;
        }
        set
        {
            this.userSexField = value;
        }
    }

    /// <remarks/>
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }

    /// <remarks/>
    public int ShareLocation
    {
        get
        {
            return this.shareLocationField;
        }
        set
        {
            this.shareLocationField = value;
        }
    }

    /// <remarks/>
    public string UserNickName
    {
        get
        {
            return this.userNickNameField;
        }
        set
        {
            this.userNickNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] UserHeadPic
    {
        get
        {
            return this.userHeadPicField;
        }
        set
        {
            this.userHeadPicField = value;
        }
    }

    /// <remarks/>
    public double UserLat
    {
        get
        {
            return this.userLatField;
        }
        set
        {
            this.userLatField = value;
        }
    }

    /// <remarks/>
    public double UserLon
    {
        get
        {
            return this.userLonField;
        }
        set
        {
            this.userLonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UserInterest")]
    public int[] UserInterest
    {
        get
        {
            return this.userInterestField;
        }
        set
        {
            this.userInterestField = value;
        }
    }

    /// <remarks/>
    public string ThirdAccount
    {
        get
        {
            return this.thirdAccountField;
        }
        set
        {
            this.thirdAccountField = value;
        }
    }

    /// <remarks/>
    public string DeviceID
    {
        get
        {
            return this.deviceIDField;
        }
        set
        {
            this.deviceIDField = value;
        }
    }

    /// <remarks/>
    public int IsOnline
    {
        get
        {
            return this.isOnlineField;
        }
        set
        {
            this.isOnlineField = value;
        }
    }

    /// <remarks/>
    public System.DateTime LastOnline
    {
        get
        {
            return this.lastOnlineField;
        }
        set
        {
            this.lastOnlineField = value;
        }
    }

    /// <remarks/>
    public int ProvinceID
    {
        get
        {
            return this.provinceIDField;
        }
        set
        {
            this.provinceIDField = value;
        }
    }

    /// <remarks/>
    public string ProvinceName
    {
        get
        {
            return this.provinceNameField;
        }
        set
        {
            this.provinceNameField = value;
        }
    }

    /// <remarks/>
    public int CityID
    {
        get
        {
            return this.cityIDField;
        }
        set
        {
            this.cityIDField = value;
        }
    }

    /// <remarks/>
    public string CityName
    {
        get
        {
            return this.cityNameField;
        }
        set
        {
            this.cityNameField = value;
        }
    }

    /// <remarks/>
    public decimal UserBalance
    {
        get
        {
            return this.userBalanceField;
        }
        set
        {
            this.userBalanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class GetUserInfoResponse : UserInfoEntity
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class FriendsRequest : IReturn<FriendsResponse>
{

    private string userPhoneField;

    private RequestHead headField;

    /// <remarks/>
    public string UserPhone
    {
        get
        {
            return this.userPhoneField;
        }
        set
        {
            this.userPhoneField = value;
        }
    }

    /// <remarks/>
    public RequestHead Head
    {
        get
        {
            return this.headField;
        }
        set
        {
            this.headField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class FriendsResponse
{

    private List<FriendsEntity> friendListField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FriendList")]
    public List<FriendsEntity> FriendList
    {
        get
        {
            return this.friendListField;
        }
        set
        {
            this.friendListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UserRegisterRequest : IReturn<UserRegisterResponse>
{

    private UserInfoEntity userRegisterField;

    /// <remarks/>
    public UserInfoEntity UserRegister
    {
        get
        {
            return this.userRegisterField;
        }
        set
        {
            this.userRegisterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UserRegisterResponse
{

    private int resultField;

    /// <remarks/>
    public int Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UpdateUserInfoRequest : IReturn<UpdateUserInfoResponse>
{

    private UserInfoEntity updateUserInfoField;

    private RequestHead headField;

    /// <remarks/>
    public UserInfoEntity UpdateUserInfo
    {
        get
        {
            return this.updateUserInfoField;
        }
        set
        {
            this.updateUserInfoField = value;
        }
    }

    /// <remarks/>
    public RequestHead Head
    {
        get
        {
            return this.headField;
        }
        set
        {
            this.headField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UpdateUserInfoResponse
{

    private int resultField;

    /// <remarks/>
    public int Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class RechargeLogRequest : IReturn<RechargeLogResponse>
{

    private string userPhoneField;

    private RequestHead headField;

    /// <remarks/>
    public string UserPhone
    {
        get
        {
            return this.userPhoneField;
        }
        set
        {
            this.userPhoneField = value;
        }
    }

    /// <remarks/>
    public RequestHead Head
    {
        get
        {
            return this.headField;
        }
        set
        {
            this.headField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class RechargeLogResponse
{

    private RechargeLogEntity[] rechargeLogsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RechargeLogs")]
    public RechargeLogEntity[] RechargeLogs
    {
        get
        {
            return this.rechargeLogsField;
        }
        set
        {
            this.rechargeLogsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UserRecordLogRequest : IReturn<UserRecordLogResponse>
{

    private string userPhoneField;

    private RequestHead headField;

    /// <remarks/>
    public string UserPhone
    {
        get
        {
            return this.userPhoneField;
        }
        set
        {
            this.userPhoneField = value;
        }
    }

    /// <remarks/>
    public RequestHead Head
    {
        get
        {
            return this.headField;
        }
        set
        {
            this.headField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UserRecordLogResponse
{

    private UserRecordLogEntity[] userRecordLogsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UserRecordLogs")]
    public UserRecordLogEntity[] UserRecordLogs
    {
        get
        {
            return this.userRecordLogsField;
        }
        set
        {
            this.userRecordLogsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UpdateFriendsRequest : IReturn<UpdateFriendsRequest>
{

    private RequestHead headField;

    private string userPhoneField;

    private string friendPhoneField;

    private int addResultField;

    /// <remarks/>
    public RequestHead Head
    {
        get
        {
            return this.headField;
        }
        set
        {
            this.headField = value;
        }
    }

    /// <remarks/>
    public string UserPhone
    {
        get
        {
            return this.userPhoneField;
        }
        set
        {
            this.userPhoneField = value;
        }
    }

    /// <remarks/>
    public string FriendPhone
    {
        get
        {
            return this.friendPhoneField;
        }
        set
        {
            this.friendPhoneField = value;
        }
    }

    /// <remarks/>
    public int AddResult
    {
        get
        {
            return this.addResultField;
        }
        set
        {
            this.addResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class UpdateFriendsResponse
{

    private int resultField;

    /// <remarks/>
    public int Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class VerificationCodeRequest : IReturn<VerificationCodeResponse>
{

    private RequestHead headField;

    private string userPhoneField;

    private string verificationCodeField;

    /// <remarks/>
    public RequestHead Head
    {
        get
        {
            return this.headField;
        }
        set
        {
            this.headField = value;
        }
    }

    /// <remarks/>
    public string UserPhone
    {
        get
        {
            return this.userPhoneField;
        }
        set
        {
            this.userPhoneField = value;
        }
    }

    /// <remarks/>
    public string VerificationCode
    {
        get
        {
            return this.verificationCodeField;
        }
        set
        {
            this.verificationCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class VerificationCodeResponse
{

    private string verificationCodeField;

    private int resultField;

    /// <remarks/>
    public string VerificationCode
    {
        get
        {
            return this.verificationCodeField;
        }
        set
        {
            this.verificationCodeField = value;
        }
    }

    /// <remarks/>
    public int Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

